#+TITLE: UI Model for Scheduling

** What are the components?
We basically have two type of components. 
- Scheduling system buttons
- Environment buttons

The above two kind of buttons again have different purposes and functions. 

** What are available to the student?
*** Buttons in the environment subsystem
- The "tick" button
  This button works all the time. Onclick, one cycle of the system is completed. This click is enbaled always, when the CPU is active, when it is idle, when we want to schedule, when we are waiting for IO etc.. The user needs to understand that the system is efficient only when CPU is not idle and wasting the clock cycles. The experiment hence provides the functionalities that can help the CPU work at maximum efficieny.
- The "New process" button
This button helps the student to create a new process with a burst time anywhere between 1 to 30cycles. But clicking this button itself is not enough. In a real system, all these functionalities happen only when a cycle is done. For this we need the tick button discussed above. The student have to complete one clock cycle when needed to execute the functionality of "New process".
- The "Terminate" button
This button terminates the currently running process on the CPU. This too needs a clock cycle to complete it's function. Hence the student have to choose "tick" after selecting the "Terminate" button.
*** Buttons in the shceduling subsystem
- Choose the scheduling algorithm
Student is free to choose and change the shceduling algorithm during the experiment. The other options like timer count will be enabled depending on the algorithm.
